exclude:
  - cronicas/

  https://github.com/Wilkner/bloguin/blob/main/cronicas/criacao-tem-valor.md
  https://wilkner.github.io/bloguin/cronicas/criacao-tem-valor.md


  cronicas/criacao-tem-valor.md

